services:
  # Next.js Frontend
  - type: web
    name: eduai-web
    runtime: node
    plan: free
    buildCommand: cd apps/web && npm install && npm run build
    startCommand: cd apps/web && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        fromService:
          type: web
          name: eduai-api
          property: host

  # NestJS API
  - type: web
    name: eduai-api
    runtime: node
    plan: free
    buildCommand: cd apps/api && npm install && npm run build
    startCommand: cd apps/api && npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: eduai-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 10000

  # PostgreSQL Database
databases:
  - name: eduai-db
    plan: free
    databaseName: eduai
    user: eduai_user
